/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chinese;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author michaeltham
 */
public class AnalyzeText extends javax.swing.JFrame {
    
    DataModel d = new DataModel();
    Text t;
    ArrayList<Vocab> vocab; 
    DefaultTableModel model;
    
    
    
 
    public AnalyzeText(Text text) {
        initComponents();
        model = (DefaultTableModel) qTable.getModel();
        d.addConnection();
        this.t = text; 
        vocab = d.getQuizWords(text);
        DefaultTableModel model = (DefaultTableModel) qTable.getModel(); 
       
        for(int i=0; i < vocab.size(); i++) {
          
            Vocab vocabobj = vocab.get(i);
            //qTable.getModel().setValueAt(vocabobj.word,i,0);
            System.out.println(vocabobj.word);
            String[] row = {vocabobj.word, vocabobj.difficulty};
            model.addRow(row);
            //qTable.getModel().setValueAt(vocabobj.difficulty,i,1);
        }
        
        difficultyDisplay.setText("Text difficulty: " + t.getDifficulty());
        
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        playQuiz = new javax.swing.JButton();
        deleteWord = new javax.swing.JButton();
        returnHome = new javax.swing.JButton();
        difficulty = new javax.swing.JComboBox<>();
        word = new javax.swing.JLabel();
        wordWanted = new javax.swing.JTextField();
        addWord = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        qTable = new javax.swing.JTable();
        difficultyDisplay = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playQuiz.setText("Play Quiz");
        playQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playQuizActionPerformed(evt);
            }
        });

        deleteWord.setText("Delete");
        deleteWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteWordActionPerformed(evt);
            }
        });

        returnHome.setText("Return");
        returnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnHomeActionPerformed(evt);
            }
        });

        difficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "easy ", "medium ", "hard" }));
        difficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyActionPerformed(evt);
            }
        });

        word.setText("Word: ");

        wordWanted.setText("*Here* ");

        addWord.setText("Add");
        addWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordActionPerformed(evt);
            }
        });

        qTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Word", "Difficulty"
            }
        ));
        jScrollPane1.setViewportView(qTable);

        difficultyDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        difficultyDisplay.setText("Text Difficulty: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(difficultyDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(returnHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(word)
                                .addGap(18, 18, 18)
                                .addComponent(wordWanted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addWord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteWord, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playQuiz)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(returnHome)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(word)
                            .addComponent(wordWanted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addWord)
                            .addComponent(deleteWord))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(difficultyDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addComponent(playQuiz))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playQuizActionPerformed
      
        this.dispose();
        Quiz obj = new Quiz(vocab,t);
        obj.setVisible(true); 
        
    }//GEN-LAST:event_playQuizActionPerformed

    private void deleteWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteWordActionPerformed
        // TODO add your handling code here:
      
        //deletes word from table
        int i = qTable.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) qTable.getModel();
        dtm.removeRow(i);
        
        //deletes word from arraylist 
        vocab.remove(i);
        
    }//GEN-LAST:event_deleteWordActionPerformed

    private void difficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultyActionPerformed

    private void addWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordActionPerformed
        
        String word = wordWanted.getText();
        String diff = (String) difficulty.getSelectedItem();
        
        // adds word to table
        String[] row = {word, diff};
        model.addRow(row);

        // adds word to ArrayList
        Vocab v = new Vocab();
        v.word = word; 
        v.difficulty = diff;
        vocab.add(v);
     
    }//GEN-LAST:event_addWordActionPerformed

    private void returnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnHomeActionPerformed
        // TODO add your handling code here:
        this.hide();
        Home obj = new Home();
        obj.setVisible(true);
    }//GEN-LAST:event_returnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            Text text = new Text(); 
            text.setId(2);
            new AnalyzeText(text).setVisible(true);
            
            }
        });
       
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWord;
    private javax.swing.JButton deleteWord;
    private javax.swing.JComboBox<String> difficulty;
    private javax.swing.JLabel difficultyDisplay;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton playQuiz;
    private javax.swing.JTable qTable;
    private javax.swing.JButton returnHome;
    private javax.swing.JLabel word;
    private javax.swing.JTextField wordWanted;
    // End of variables declaration//GEN-END:variables
}
