/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chinese;

import java.util.ArrayList;

/**
 *
 * @author michaeltham
 */
public class Quiz extends javax.swing.JFrame {
    ArrayList <Vocab> allWords = new ArrayList();
    ArrayList <Vocab> wrongWords = new ArrayList();
    ArrayList <Integer> timesWrong = new ArrayList();
    int score; 
    int i = -1; 
    int totalWords; 
    DataModel d = new DataModel();
    Text text;
    

    /**
     * Creates new form Quiz
     */
    public Quiz(ArrayList <Vocab> vocab, Text text) {
        initComponents();
        d.addConnection();
        this.allWords = vocab; 
        this.text = text;
        totalWords = vocab.size();
        progressBar.setMaximum(allWords.size());
       
        //get word out of vocab object and display 
        nextWord();
        d.updateScore(text);

    }
    
    public boolean nextWord(){ 
        
        if ( i >= allWords.size()-1){ 
            endQuiz();
            return false;
        } else {
            i++; 
            Vocab word = allWords.get(i);
            displayWord.setText(word.word);
            return true;
        }
        
    }
    
    public void endQuiz(){ 
        
        for(int i = wrongWords.size()-1;i >= 0;i--){
            if (timesWrong.get(i) <= 3){ 
                wrongWords.remove(i);
            } 
        }
        //updates prevScore for text object
        text.setPrevScore((score / totalWords) * 100);
        // updates prevScore in databse
        d.updateScore(text);
        // removes word from arrayList then prints it on QuizEnd page 
        this.dispose();
        QuizEnd obj = new QuizEnd(wrongWords,score,totalWords);
        obj.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        correctWord = new javax.swing.JButton();
        wrongWord = new javax.swing.JButton();
        skip = new javax.swing.JButton();
        quizTime = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        displayWord = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        correctWord.setText("Correct");
        correctWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctWordActionPerformed(evt);
            }
        });

        wrongWord.setText("Wrong");
        wrongWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrongWordActionPerformed(evt);
            }
        });

        skip.setText("Skip");
        skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipActionPerformed(evt);
            }
        });

        quizTime.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        quizTime.setText("Quiz Time!");

        displayWord.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        displayWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayWord.setText("Chinese Word Here ");

        jLabel2.setText("Progress:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(correctWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(wrongWord)
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(skip))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizTime, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(displayWord, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quizTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(displayWord, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctWord)
                    .addComponent(wrongWord))
                .addComponent(skip))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void correctWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctWordActionPerformed
        // TODO add your handling code here:
        Vocab word = allWords.get(i);
        
        if (!wrongWords.contains(word)){
            score++;
        }
         nextWord();
         progressBar.setValue(progressBar.getValue()+1);
   
    }//GEN-LAST:event_correctWordActionPerformed

    private void wrongWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrongWordActionPerformed
        
        Vocab word = allWords.get(i);
       
        if(wrongWords.contains(word)){  
            // gets index of wrongWord from wrongWord arraylist then in timesWrong ArrayList, increases the timesWrong by 1
            int index = wrongWords.indexOf(word); 
            timesWrong.set(index, timesWrong.get(index)+1);
        } else{ 
            wrongWords.add(word);
            timesWrong.add(1);      
        }
        //if word is wrong and only have 3 or less words left to test
        if(allWords.size()-i <= 3){ 
           
            allWords.add(word);
            
        } else{  
            allWords.add(i+3,word);    
        }

        nextWord();
        progressBar.setMaximum(allWords.size());
        progressBar.setValue(progressBar.getValue()+1);
       
    }//GEN-LAST:event_wrongWordActionPerformed

    private void skipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipActionPerformed
        // TODO add your handling code here:
        nextWord();
        progressBar.setValue(progressBar.getValue()+1);
        
    }//GEN-LAST:event_skipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz(new ArrayList<Vocab>(), new Text()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton correctWord;
    private javax.swing.JLabel displayWord;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel quizTime;
    private javax.swing.JButton skip;
    private javax.swing.JButton wrongWord;
    // End of variables declaration//GEN-END:variables
}
